# Generated by Django 3.2.9 on 2021-12-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/photos/%Y/%m/%d/', verbose_name='Картинка'),
        ),
    ]
