# Generated by Django 3.2.9 on 2021-12-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_news_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Ссылка'),
        ),
    ]
