# Generated by Django 3.2.9 on 2021-11-30 16:14

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Фамилия')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Почта')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('function', models.BooleanField(default=True, verbose_name='Работает')),
                ('about', models.TextField(blank=True, verbose_name='Примечания')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('adress', models.CharField(blank=True, max_length=254, verbose_name='Адрес')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('function', models.BooleanField(default=True, verbose_name='Работает')),
                ('about', models.TextField(blank=True, verbose_name='Примечания')),
                ('date_joined', models.DateField()),
                ('price_type', models.CharField(choices=[('Р', 'Розница'), ('М', 'Мелкий опт'), ('О', 'Опт'), ('Д', 'Дистрибьюция')], max_length=1, verbose_name='Тип цен')),
                ('contact', models.ManyToManyField(blank=True, to='crm.Person')),
            ],
        ),
    ]
