# Generated by Django 4.0 on 2022-01-02 14:57

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Ссылка')),
                ('adress', models.CharField(blank=True, max_length=254, verbose_name='Адрес')),
                ('status', models.CharField(blank=True, choices=[('Новый', 'Новый'), ('Текущий', 'Текущий'), ('Потенциальный', 'Потенциальный'), ('Контакт из почты', 'Контакт из почты'), ('Архив', 'Архив')], max_length=20, verbose_name='Cтатус')),
                ('date_joined', models.DateField(blank=True, verbose_name='Начало работы')),
                ('price_type', models.CharField(blank=True, choices=[('И', 'Интернет'), ('Р', 'Розница'), ('М', 'Мелкий опт'), ('О', 'Опт'), ('Д', 'Дистрибьюция')], max_length=1, verbose_name='Тип цен')),
                ('delivery', models.CharField(blank=True, choices=[('Всеволожск', 'ежедневно'), ('Север и цетр', 'вторник, четверг, суббота'), ('Юг', 'понедельник, среда, пятница'), ('Пригород', 'среда'), ('Регион', 'регион')], max_length=12, verbose_name='Развозка')),
                ('about', models.TextField(blank=True, verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Фамилия')),
                ('position', models.CharField(blank=True, choices=[('Учредитель', 'Учредитель'), ('Администратор', 'Администратор'), ('Сверки', 'Сверки')], max_length=15, verbose_name='Должность')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Почта')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Телефон')),
                ('exist', models.BooleanField(default=True, verbose_name='Работает')),
                ('contact', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='crm.client')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
