# Generated by Django 4.0 on 2022-01-03 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('special_status', 'Can view all clients')], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': [('special_status', 'Can view all persons')], 'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
    ]
