# Generated by Django 3.2.9 on 2021-11-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='position',
            field=models.CharField(blank=True, choices=[('Учредитель', 'Учредитель'), ('Администратор', 'Администратор'), ('Сверки', 'Сверки')], max_length=15, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_joined',
            field=models.DateField(blank=True, verbose_name='Начало работы'),
        ),
    ]
