# Generated by Django 3.2.9 on 2021-11-30 16:55

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20211130_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='function',
            new_name='exist',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='function',
            new_name='exist',
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Телефон'),
        ),
    ]
