# Generated by Django 4.0 on 2022-01-04 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_client_options_alter_person_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('special_status', 'Просмотр всех clients')], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': [('special_status', 'Просмотр всех persons')], 'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
    ]
