# Generated by Django 4.0 on 2022-01-04 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_client_options_alter_person_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
    ]
