# Generated by Django 3.2.9 on 2021-11-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_client_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='exist',
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(blank=True, choices=[('Новый', 'Новый'), ('Текущий', 'Текущий'), ('Потенциальный', 'Потенциальный'), ('Контакт из почты', 'Контакт из почты'), ('Архив', 'Архив')], max_length=20, verbose_name='Cтатус'),
        ),
        migrations.AlterField(
            model_name='client',
            name='delivery',
            field=models.CharField(blank=True, choices=[('Всеволожск', 'ежедневно'), ('Север и цетр', 'вторник, четверг, суббота'), ('Юг', 'понедельник, среда, пятница'), ('Пригород', 'среда'), ('Регион', 'регион')], max_length=12, verbose_name='Развозка'),
        ),
        migrations.AlterField(
            model_name='client',
            name='price_type',
            field=models.CharField(choices=[('И', 'Интернет'), ('Р', 'Розница'), ('М', 'Мелкий опт'), ('О', 'Опт'), ('Д', 'Дистрибьюция')], max_length=1, verbose_name='Тип цен'),
        ),
    ]
