# Generated by Django 3.2.9 on 2021-12-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20211130_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='slug',
            field=models.SlugField(default='pf', max_length=40, unique=True, verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
