# Generated by Django 3.2.9 on 2021-12-01 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_client_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='contact',
        ),
        migrations.AddField(
            model_name='person',
            name='contact',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.client'),
            preserve_default=False,
        ),
    ]
