# Generated by Django 3.2.9 on 2021-12-01 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_remove_person_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
    ]
