# Generated by Django 3.2.9 on 2021-12-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_remove_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='price_type',
            field=models.CharField(blank=True, choices=[('И', 'Интернет'), ('Р', 'Розница'), ('М', 'Мелкий опт'), ('О', 'Опт'), ('Д', 'Дистрибьюция')], max_length=1, verbose_name='Тип цен'),
        ),
    ]
